import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';
import { FeedCardComponent } from './feed-card/feed-card.component';
import { ComponentsModule } from '../../components/components.module';
import { FeedComponent } from './feed/feed.component';
import { PickEmojiComponent } from './pick-emoji/pick-emoji.component';
import { PickerModule } from '@ctrl/ngx-emoji-mart';
import { MatIconModule } from '@angular/material/icon';
import { FeedRoutingModule } from './feed-routing-module';
import { MatButtonModule } from '@angular/material/button';
import { MatProgressSpinnerModule } from '@angular/material/progress-spinner';
import { HighlightModule, HIGHLIGHT_OPTIONS } from 'ngx-highlightjs';
import { TranslateModule } from '@ngx-translate/core';
import { MatTooltipModule } from '@angular/material/tooltip';
import { ScriptEvaluationModule } from '../../components/script-evaluation/script-evaluation.module';

@NgModule({
  declarations: [FeedCardComponent, FeedComponent, PickEmojiComponent],
  exports: [FeedComponent, FeedCardComponent],
  imports: [
    CommonModule,
    FeedRoutingModule,
    ComponentsModule,
    ScriptEvaluationModule,
    PickerModule,
    MatIconModule,
    MatButtonModule,
    MatProgressSpinnerModule,
    HighlightModule,
    TranslateModule,
    MatTooltipModule
  ],
  providers: [
    {
      provide: HIGHLIGHT_OPTIONS,
      useValue: {
        coreLibraryLoader: () => import('highlight.js/lib/core'),
        languages: {
          csp: () => import('highlight.js/lib/languages/csp'),
          excel: () => import('highlight.js/lib/languages/excel'),
          hsp: () => import('highlight.js/lib/languages/hsp'),
          basic: () => import('highlight.js/lib/languages/basic'),
          less: () => import('highlight.js/lib/languages/less'),
          n1ql: () => import('highlight.js/lib/languages/n1ql'),
          profile: () => import('highlight.js/lib/languages/profile'),
          sas: () => import('highlight.js/lib/languages/sas'),
          tcl: () => import('highlight.js/lib/languages/tcl'),
          abnf: () => import('highlight.js/lib/languages/abnf'),
          bnf: () => import('highlight.js/lib/languages/bnf'),
          css: () => import('highlight.js/lib/languages/css'),
          fix: () => import('highlight.js/lib/languages/fix'),
          htmlbars: () => import('highlight.js/lib/languages/htmlbars'),
          lisp: () => import('highlight.js/lib/languages/lisp'),
          nginx: () => import('highlight.js/lib/languages/nginx'),
          prolog: () => import('highlight.js/lib/languages/prolog'),
          scala: () => import('highlight.js/lib/languages/scala'),
          thrift: () => import('highlight.js/lib/languages/thrift'),
          accesslog: () => import('highlight.js/lib/languages/accesslog'),
          brainfuck: () => import('highlight.js/lib/languages/brainfuck'),
          d: () => import('highlight.js/lib/languages/d'),
          flix: () => import('highlight.js/lib/languages/flix'),
          http: () => import('highlight.js/lib/languages/http'),
          nim: () => import('highlight.js/lib/languages/nim'),
          properties: () => import('highlight.js/lib/languages/properties'),
          scheme: () => import('highlight.js/lib/languages/scheme'),
          tp: () => import('highlight.js/lib/languages/tp'),
          actionscript: () => import('highlight.js/lib/languages/actionscript'),
          clike: () => import('highlight.js/lib/languages/c-like'),
          dart: () => import('highlight.js/lib/languages/dart'),
          fortran: () => import('highlight.js/lib/languages/fortran'),
          hy: () => import('highlight.js/lib/languages/hy'),
          livescript: () => import('highlight.js/lib/languages/livescript'),
          nix: () => import('highlight.js/lib/languages/nix'),
          protobuf: () => import('highlight.js/lib/languages/protobuf'),
          scilab: () => import('highlight.js/lib/languages/scilab'),
          twig: () => import('highlight.js/lib/languages/twig'),
          ada: () => import('highlight.js/lib/languages/ada'),
          c: () => import('highlight.js/lib/languages/c'),
          delphi: () => import('highlight.js/lib/languages/delphi'),
          fsharp: () => import('highlight.js/lib/languages/fsharp'),
          inform7: () => import('highlight.js/lib/languages/inform7'),
          llvm: () => import('highlight.js/lib/languages/llvm'),
          nsis: () => import('highlight.js/lib/languages/nsis'),
          puppet: () => import('highlight.js/lib/languages/puppet'),
          scss: () => import('highlight.js/lib/languages/scss'),
          typescript: () => import('highlight.js/lib/languages/typescript'),
          angelscript: () => import('highlight.js/lib/languages/angelscript'),
          cal: () => import('highlight.js/lib/languages/cal'),
          diff: () => import('highlight.js/lib/languages/diff'),
          gams: () => import('highlight.js/lib/languages/gams'),
          ini: () => import('highlight.js/lib/languages/ini'),
          objectivec: () => import('highlight.js/lib/languages/objectivec'),
          purebasic: () => import('highlight.js/lib/languages/purebasic'),
          shell: () => import('highlight.js/lib/languages/shell'),
          vala: () => import('highlight.js/lib/languages/vala'),
          apache: () => import('highlight.js/lib/languages/apache'),
          capnproto: () => import('highlight.js/lib/languages/capnproto'),
          django: () => import('highlight.js/lib/languages/django'),
          irpf90: () => import('highlight.js/lib/languages/irpf90'),
          lua: () => import('highlight.js/lib/languages/lua'),
          ocaml: () => import('highlight.js/lib/languages/ocaml'),
          pythonrepl: () => import('highlight.js/lib/languages/python-repl'),
          smali: () => import('highlight.js/lib/languages/smali'),
          vbnet: () => import('highlight.js/lib/languages/vbnet'),
          applescript: () => import('highlight.js/lib/languages/applescript'),
          ceylon: () => import('highlight.js/lib/languages/ceylon'),
          dns: () => import('highlight.js/lib/languages/dns'),
          gcode: () => import('highlight.js/lib/languages/gcode'),
          makefile: () => import('highlight.js/lib/languages/makefile'),
          openscad: () => import('highlight.js/lib/languages/openscad'),
          python: () => import('highlight.js/lib/languages/python'),
          smalltalk: () => import('highlight.js/lib/languages/smalltalk'),
          vbscripthtml: () => import('highlight.js/lib/languages/vbscript-html'),
          arcade: () => import('highlight.js/lib/languages/arcade'),
          clean: () => import('highlight.js/lib/languages/clean'),
          dockerfile: () => import('highlight.js/lib/languages/dockerfile'),
          gherkin: () => import('highlight.js/lib/languages/gherkin'),
          java: () => import('highlight.js/lib/languages/java'),
          markdown: () => import('highlight.js/lib/languages/markdown'),
          oxygene: () => import('highlight.js/lib/languages/oxygene'),
          q: () => import('highlight.js/lib/languages/q'),
          sml: () => import('highlight.js/lib/languages/sml'),
          vbscript: () => import('highlight.js/lib/languages/vbscript'),
          arduino: () => import('highlight.js/lib/languages/arduino'),
          clojurerepl: () => import('highlight.js/lib/languages/clojure-repl'),
          dos: () => import('highlight.js/lib/languages/dos'),
          glsl: () => import('highlight.js/lib/languages/glsl'),
          javascript: () => import('highlight.js/lib/languages/javascript'),
          parser3: () => import('highlight.js/lib/languages/parser3'),
          qml: () => import('highlight.js/lib/languages/qml'),
          verilog: () => import('highlight.js/lib/languages/verilog'),
          armasm: () => import('highlight.js/lib/languages/armasm'),
          clojure: () => import('highlight.js/lib/languages/clojure'),
          dsconfig: () => import('highlight.js/lib/languages/dsconfig'),
          jbosscli: () => import('highlight.js/lib/languages/jboss-cli'),
          matlab: () => import('highlight.js/lib/languages/matlab'),
          perl: () => import('highlight.js/lib/languages/perl'),
          r: () => import('highlight.js/lib/languages/r'),
          sql: () => import('highlight.js/lib/languages/sql'),
          vhdl: () => import('highlight.js/lib/languages/vhdl'),
          asciidoc: () => import('highlight.js/lib/languages/asciidoc'),
          cmake: () => import('highlight.js/lib/languages/cmake'),
          dts: () => import('highlight.js/lib/languages/dts'),
          go: () => import('highlight.js/lib/languages/go'),
          json: () => import('highlight.js/lib/languages/json'),
          pf: () => import('highlight.js/lib/languages/pf'),
          reasonml: () => import('highlight.js/lib/languages/reasonml'),
          stan: () => import('highlight.js/lib/languages/stan'),
          aspectj: () => import('highlight.js/lib/languages/aspectj'),
          coffeescript: () => import('highlight.js/lib/languages/coffeescript'),
          dust: () => import('highlight.js/lib/languages/dust'),
          golo: () => import('highlight.js/lib/languages/golo'),
          juliarepl: () => import('highlight.js/lib/languages/julia-repl'),
          pgsql: () => import('highlight.js/lib/languages/pgsql'),
          rib: () => import('highlight.js/lib/languages/rib'),
          autohotkey: () => import('highlight.js/lib/languages/autohotkey'),
          coq: () => import('highlight.js/lib/languages/coq'),
          ebnf: () => import('highlight.js/lib/languages/ebnf'),
          gradle: () => import('highlight.js/lib/languages/gradle'),
          julia: () => import('highlight.js/lib/languages/julia'),
          mercury: () => import('highlight.js/lib/languages/mercury'),
          phptemplate: () => import('highlight.js/lib/languages/php-template'),
          roboconf: () => import('highlight.js/lib/languages/roboconf'),
          step21: () => import('highlight.js/lib/languages/step21'),
          xl: () => import('highlight.js/lib/languages/xl'),
          autoit: () => import('highlight.js/lib/languages/autoit'),
          cos: () => import('highlight.js/lib/languages/cos'),
          elixir: () => import('highlight.js/lib/languages/elixir'),
          groovy: () => import('highlight.js/lib/languages/groovy'),
          kotlin: () => import('highlight.js/lib/languages/kotlin'),
          mipsasm: () => import('highlight.js/lib/languages/mipsasm'),
          php: () => import('highlight.js/lib/languages/php'),
          routeros: () => import('highlight.js/lib/languages/routeros'),
          stylus: () => import('highlight.js/lib/languages/stylus'),
          xml: () => import('highlight.js/lib/languages/xml'),
          avrasm: () => import('highlight.js/lib/languages/avrasm'),
          cpp: () => import('highlight.js/lib/languages/cpp'),
          elm: () => import('highlight.js/lib/languages/elm'),
          haml: () => import('highlight.js/lib/languages/haml'),
          lasso: () => import('highlight.js/lib/languages/lasso'),
          mizar: () => import('highlight.js/lib/languages/mizar'),
          plaintext: () => import('highlight.js/lib/languages/plaintext'),
          rsl: () => import('highlight.js/lib/languages/rsl'),
          subunit: () => import('highlight.js/lib/languages/subunit'),
          xquery: () => import('highlight.js/lib/languages/xquery'),
          awk: () => import('highlight.js/lib/languages/awk'),
          crmsh: () => import('highlight.js/lib/languages/crmsh'),
          erb: () => import('highlight.js/lib/languages/erb'),
          handlebars: () => import('highlight.js/lib/languages/handlebars'),
          latex: () => import('highlight.js/lib/languages/latex'),
          mojolicious: () => import('highlight.js/lib/languages/mojolicious'),
          pony: () => import('highlight.js/lib/languages/pony'),
          ruby: () => import('highlight.js/lib/languages/ruby'),
          swift: () => import('highlight.js/lib/languages/swift'),
          yaml: () => import('highlight.js/lib/languages/yaml'),
          axapta: () => import('highlight.js/lib/languages/axapta'),
          crystal: () => import('highlight.js/lib/languages/crystal'),
          erlangrepl: () => import('highlight.js/lib/languages/erlang-repl'),
          haskell: () => import('highlight.js/lib/languages/haskell'),
          ldif: () => import('highlight.js/lib/languages/ldif'),
          monkey: () => import('highlight.js/lib/languages/monkey'),
          powershell: () => import('highlight.js/lib/languages/powershell'),
          ruleslanguage: () => import('highlight.js/lib/languages/ruleslanguage'),
          taggerscript: () => import('highlight.js/lib/languages/taggerscript'),
          zephir: () => import('highlight.js/lib/languages/zephir'),
          bash: () => import('highlight.js/lib/languages/bash'),
          csharp: () => import('highlight.js/lib/languages/csharp'),
          erlang: () => import('highlight.js/lib/languages/erlang'),
          haxe: () => import('highlight.js/lib/languages/haxe'),
          leaf: () => import('highlight.js/lib/languages/leaf'),
          moonscript: () => import('highlight.js/lib/languages/moonscript'),
          processing: () => import('highlight.js/lib/languages/processing'),
          rust: () => import('highlight.js/lib/languages/rust'),
          tap: () => import('highlight.js/lib/languages/tap')
        }
      }
    }
  ]
})
export class FeedModule {}
