version: '3.3'
services:
  postgres:
    image: postgres:12
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: U3JP2qFaNE2Wa6zg
    volumes:
      - hasura2_db_data:/var/lib/postgresql/data
  graphql-engine:
    image: hasura/graphql-engine:v1.2.2
    ports:
      - target: 8080
        published: 8080
        mode: host
    depends_on:
      - "postgres"
    restart: always
    environment:
      HASURA_GRAPHQL_DATABASE_URL: postgres://postgres:U3JP2qFaNE2Wa6zg@postgres:5432/postgres
      HASURA_GRAPHQL_ENABLE_CONSOLE: "false" # set to "false" to disable console
      HASURA_GRAPHQL_ENABLED_LOG_TYPES: startup, http-log, webhook-log, websocket-log, query-log
      HASURA_GRAPHQL_UNAUTHORIZED_ROLE: anonymous
      HASURA_GRAPHQL_ENABLE_TELEMETRY: "false"
      HASURA_GRAPHQL_JWT_SECRET: '{"type":"RS256", "jwk_url": "https://www.googleapis.com/service_accounts/v1/jwk/securetoken@system.gserviceaccount.com", "audience": "snippeter", "issuer": "https://securetoken.google.com/snippeter"}'
      ## enable allowlist for specified queries
      # HASURA_GRAPHQL_ENABLE_ALLOWLIST: "true"
      ## uncomment next line to set an admin secret
      HASURA_GRAPHQL_ADMIN_SECRET: hAdminsura
volumes:
  hasura2_db_data:
